language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: IwXkMUvUSkE17tcSPfzGXXO9g2z4A8klldZNv0pMFyjZOa7XyCS3dDtTZt7BR2UKV1M1eaV7YSAEOQRg80bpuIbWlKhhb0ujOJVNxkcUNTuBiFq1ElG/otDv7yLZMgJtfSPMWxsnpSgoG0nfCaMvX+OREeoqOkRAcbIqFE1634qa7u/LzfAcWdUKdZN8I6Ac4Oxblqe07ZXQrSWvXrEHNjzrnkHTMt8qY4qhzAe4DROvB0IyMgr3C3RfBsAJ6K/p5vOV8rpLHZ0Pghuu98MS+1bAslx2uVlWVF0gqpeoVCEWP5JR5dz72P4zOTkdxKKWNKtwkwZJw/u7R6wUzBorBBrrhjeI59Q/pzdAq9nCQAPt7Wt6U4EKLtaQTLunmVVjyOxUMjcL8qwTacjjsluiaYXa1nz9dJ4mD0U0luvlF7vECimRP6QL3BGRlYkIZxAFPg/b6JiQX5WZZGg6/7nIJDW8THjgvANuthFAPCPBk9qlPGmI22G+7vLU2oPO7alIhJGeq+bbn7FVpiIqaytoEcaiXrSxfaEp5apyS4TOSzIxgEm1DF0M3v4SacgF2MJoYpGVKBlnNOMWVF78GURlX4XefCkoPdOj3t7xOUlUt7MhRQ6RNxaDaDpDVVY3zGnA+8OGwfxm18Layf0koT41zaWHzd2JaemFAsERPr1c19I=
  app: fista-garaget
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
